name: Deploy Memoris

on: 
  push:
    branches:
      - main
            
jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
            
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/yasin_enis22/MemoriseApp
            git pull origin main
            npm install
            pm2 restart memorise
