name: Deploy Memoris

on: 
  push:
    branches:
      - main
            
jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.5.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
            
      - name: Deploy over SSH
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/yasin_enis22/MemoriseApp
            git pull origin main
            sudo pm2 restart memorise
